"""baseline schema

Revision ID: c81565f512a7
Revises: 
Create Date: 2026-08-19 14:12:13.756599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c81565f512a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_history',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('nav_count', sa.Integer(), nullable=False),
    sa.Column('nav_text', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('strategy_profile', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('ai_report', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('saved_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cta_fama_research_audits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('exit_history_complete', sa.Boolean(), nullable=False),
    sa.Column('survivorship_audit_passed', sa.Boolean(), nullable=False),
    sa.Column('backfill_audit_passed', sa.Boolean(), nullable=False),
    sa.Column('same_source_deduplicated', sa.Boolean(), nullable=False),
    sa.Column('oos_state_segments', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_snapshots',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_snapshots_label'), ['label'], unique=False)

    op.create_table('product_entities',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('standard_name', sa.String(length=256), nullable=False),
    sa.Column('manager_name', sa.String(length=256), nullable=True),
    sa.Column('strategy', sa.String(length=128), nullable=True),
    sa.Column('strategy_disclosure', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('nav_frequency', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmation_status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_by', sa.String(length=128), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('merged_into_id', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['product_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_entities_confirmation_status'), ['confirmation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_entities_manager_name'), ['manager_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_entities_merged_into_id'), ['merged_into_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_entities_standard_name'), ['standard_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_entities_strategy'), ['strategy'], unique=False)

    op.create_table('raw_files',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('report_period', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parsing_status', sa.String(length=20), nullable=False),
    sa.Column('parsing_error', sa.Text(), nullable=True),
    sa.Column('extraction_audit', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('ingestion_context', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_files_file_hash'), ['file_hash'], unique=False)

    op.create_table('recommendation_tracking',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('decision_id', sa.String(length=20), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('periods_elapsed', sa.Integer(), nullable=False),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.Column('actual_return', sa.Float(), nullable=True),
    sa.Column('return_deviation', sa.Float(), nullable=True),
    sa.Column('actual_max_drawdown', sa.Float(), nullable=True),
    sa.Column('per_product', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('breach_reasons', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('triggered_task_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision_records.id'], ),
    sa.ForeignKeyConstraint(['triggered_task_id'], ['review_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_tracking_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_tracking_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_tracking_triggered_task_id'), ['triggered_task_id'], unique=False)

    op.create_table('review_tasks',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('decision_id', sa.String(length=20), nullable=True),
    sa.Column('tracking_id', sa.String(length=20), nullable=True),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('assignee', sa.String(length=128), nullable=True),
    sa.Column('proposal', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=128), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision_records.id'], ),
    sa.ForeignKeyConstraint(['tracking_id'], ['recommendation_tracking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_tasks_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_tasks_tracking_id'), ['tracking_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('plan', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('tools_used', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('reflection', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('data_snapshot_id', sa.String(length=20), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_snapshot_id'], ['data_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_data_snapshot_id'), ['data_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_session_id'), ['session_id'], unique=False)

    op.create_table('cta_fama_product_audits',
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('source_group', sa.String(length=120), nullable=True),
    sa.Column('point_in_time_verified', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product_entities.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('document_fragments',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('file_id', sa.String(length=20), nullable=False),
    sa.Column('fragment_type', sa.String(length=32), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_data', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('product_id', sa.String(length=20), nullable=True),
    sa.Column('extraction_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['raw_files.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_fragments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_fragments_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_fragments_product_id'), ['product_id'], unique=False)

    op.create_table('product_aliases',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('alias', sa.String(length=256), nullable=False),
    sa.Column('alias_type', sa.String(length=32), nullable=False),
    sa.Column('source_file_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product_entities.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['raw_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_aliases_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_aliases_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_aliases_source_file_id'), ['source_file_id'], unique=False)

    op.create_table('decision_records',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('run_id', sa.String(length=20), nullable=True),
    sa.Column('decision_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('data_snapshot_id', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('veto_reason', sa.Text(), nullable=True),
    sa.Column('adjustment', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_snapshot_id'], ['data_snapshots.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_records_data_snapshot_id'), ['data_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_status'), ['status'], unique=False)

    op.create_table('nav_candidate_versions',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('source_file_id', sa.String(length=20), nullable=False),
    sa.Column('source_fragment_id', sa.String(length=20), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('points', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product_entities.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['raw_files.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['document_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nav_candidate_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nav_candidate_versions_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nav_candidate_versions_source_file_id'), ['source_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nav_candidate_versions_source_fragment_id'), ['source_fragment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nav_candidate_versions_status'), ['status'], unique=False)

    op.create_table('nav_observations',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Float(), nullable=False),
    sa.Column('acc_nav', sa.Float(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('source_file_id', sa.String(length=20), nullable=True),
    sa.Column('source_fragment_id', sa.String(length=20), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product_entities.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['raw_files.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['document_fragments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'observation_date', name='uq_nav_product_date')
    )
    with op.batch_alter_table('nav_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nav_observations_observation_date'), ['observation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_nav_observations_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nav_observations_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_nav_observations_source_file_id'), ['source_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nav_observations_source_fragment_id'), ['source_fragment_id'], unique=False)

    op.create_table('structured_facts',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=False),
    sa.Column('source_file_id', sa.String(length=20), nullable=True),
    sa.Column('source_fragment_id', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_version', sa.Integer(), nullable=False),
    sa.Column('superseded_by', sa.String(length=20), nullable=True),
    sa.Column('confirmation_status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_by', sa.String(length=128), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product_entities.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['raw_files.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['document_fragments.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['structured_facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('structured_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_structured_facts_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_structured_facts_source_file_id'), ['source_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_structured_facts_source_fragment_id'), ['source_fragment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_structured_facts_superseded_by'), ['superseded_by'], unique=False)

    op.create_table('tool_invocations',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('run_id', sa.String(length=20), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('input_summary', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('output_summary', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('invoked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_invocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_invocations_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_invocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_invocations_run_id'))

    op.drop_table('tool_invocations')
    with op.batch_alter_table('structured_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_structured_facts_superseded_by'))
        batch_op.drop_index(batch_op.f('ix_structured_facts_source_fragment_id'))
        batch_op.drop_index(batch_op.f('ix_structured_facts_source_file_id'))
        batch_op.drop_index(batch_op.f('ix_structured_facts_product_id'))

    op.drop_table('structured_facts')
    with op.batch_alter_table('nav_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nav_observations_source_fragment_id'))
        batch_op.drop_index(batch_op.f('ix_nav_observations_source_file_id'))
        batch_op.drop_index(batch_op.f('ix_nav_observations_review_status'))
        batch_op.drop_index(batch_op.f('ix_nav_observations_product_id'))
        batch_op.drop_index(batch_op.f('ix_nav_observations_observation_date'))

    op.drop_table('nav_observations')
    with op.batch_alter_table('nav_candidate_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nav_candidate_versions_status'))
        batch_op.drop_index(batch_op.f('ix_nav_candidate_versions_source_fragment_id'))
        batch_op.drop_index(batch_op.f('ix_nav_candidate_versions_source_file_id'))
        batch_op.drop_index(batch_op.f('ix_nav_candidate_versions_product_id'))

    op.drop_table('nav_candidate_versions')
    with op.batch_alter_table('decision_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_records_status'))
        batch_op.drop_index(batch_op.f('ix_decision_records_run_id'))
        batch_op.drop_index(batch_op.f('ix_decision_records_data_snapshot_id'))

    op.drop_table('decision_records')
    with op.batch_alter_table('product_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_aliases_source_file_id'))
        batch_op.drop_index(batch_op.f('ix_product_aliases_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_aliases_alias'))

    op.drop_table('product_aliases')
    with op.batch_alter_table('document_fragments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_fragments_product_id'))
        batch_op.drop_index(batch_op.f('ix_document_fragments_file_id'))

    op.drop_table('document_fragments')
    op.drop_table('cta_fama_product_audits')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_data_snapshot_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('review_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_tasks_tracking_id'))
        batch_op.drop_index(batch_op.f('ix_review_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_review_tasks_decision_id'))

    op.drop_table('review_tasks')
    with op.batch_alter_table('recommendation_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_tracking_triggered_task_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_tracking_status'))
        batch_op.drop_index(batch_op.f('ix_recommendation_tracking_decision_id'))

    op.drop_table('recommendation_tracking')
    with op.batch_alter_table('raw_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_files_file_hash'))

    op.drop_table('raw_files')
    with op.batch_alter_table('product_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_entities_strategy'))
        batch_op.drop_index(batch_op.f('ix_product_entities_standard_name'))
        batch_op.drop_index(batch_op.f('ix_product_entities_merged_into_id'))
        batch_op.drop_index(batch_op.f('ix_product_entities_manager_name'))
        batch_op.drop_index(batch_op.f('ix_product_entities_confirmation_status'))

    op.drop_table('product_entities')
    with op.batch_alter_table('data_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_snapshots_label'))

    op.drop_table('data_snapshots')
    op.drop_table('cta_fama_research_audits')
    op.drop_table('analysis_history')
    # ### end Alembic commands ###
